package org.openmrs.module.ugandaemrreports.model;

import org.openmrs.BaseOpenmrsMetadata;

import javax.persistence.*;
import java.util.Locale;

/**
 * Core Mamba Indicator model.
 *
 * This single entity supports:
 *
 *  - BASE      (SQL-based indicator definition)
 *  - COMPOSITE (logical composition of other indicators)
 *  - FINAL     (disaggregated/tabular output definition)
 *
 * Authoring configuration is stored in configJson (building block for future improvements).
 * Generated/executable SQL is stored in sqlTemplate / denominatorSqlTemplate for fast runtime use.
 *
 * Independent of OpenMRS Reporting module.
 */
@Entity
@Table(
        name = "mamba_indicator",
        indexes = {
                @Index(name = "idx_mamba_indicator_uuid", columnList = "uuid"),
                @Index(name = "idx_mamba_indicator_kind", columnList = "kind"),
                @Index(name = "idx_mamba_indicator_code", columnList = "code"),
                @Index(name = "idx_mamba_indicator_theme_uuid", columnList = "theme_uuid"),
                @Index(name = "idx_mamba_indicator_retired", columnList = "retired")
        }
)
public class MambaIndicator extends BaseOpenmrsMetadata {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "mamba_indicator_id")
    private Integer id;

    /**
     * Optional business code (often unique in real use).
     * Example: HMIS105_OPD_001
     *
     * NOTE: Some DBs allow multiple NULLs even with UNIQUE; that’s OK.
     */
    @Column(name = "code", unique = true, length = 100)
    private String code;

    /**
     * BASE | COMPOSITE | FINAL
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "kind", nullable = false, length = 20)
    private Kind kind;

    /**
     * Default return type when evaluated.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "default_value_type", nullable = false, length = 20)
    private ValueType defaultValueType = ValueType.NUMBER;

    /**
     * Optional link to a Data Theme (uuid). Makes UI queries faster + avoids parsing metaJson.
     */
    @Column(name = "theme_uuid", length = 38)
    private String themeUuid;

    /**
     * Authoring/building JSON configuration (kind-specific).
     * This is the "source of truth" for rebuilding SQL later.
     */
    @Lob
    @Column(name = "config_json", nullable = false)
    private String configJson;

    /**
     * Executable SQL (BASE indicators).
     * Generated by UI or backend. Stored explicitly for runtime and versioning.
     */
    @Lob
    @Column(name = "sql_template")
    private String sqlTemplate;

    /**
     * Optional denominator SQL for rate indicators (BASE).
     */
    @Lob
    @Column(name = "denominator_sql_template")
    private String denominatorSqlTemplate;

    /**
     * Free-form metadata (tags, UI hints, etc.).
     * Theme linkage should prefer themeUuid, but you can still store extra theme info here if you want.
     */
    @Lob
    @Column(name = "meta_json")
    private String metaJson;

    // -------------------------------------------------
    // BaseOpenmrsMetadata requires getId()/setId()
    // -------------------------------------------------

    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    // -------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Kind getKind() {
        return kind;
    }

    public void setKind(Kind kind) {
        this.kind = kind;
    }

    public ValueType getDefaultValueType() {
        return defaultValueType;
    }

    public void setDefaultValueType(ValueType defaultValueType) {
        this.defaultValueType = defaultValueType;
    }

    public String getThemeUuid() {
        return themeUuid;
    }

    public void setThemeUuid(String themeUuid) {
        this.themeUuid = themeUuid;
    }

    public String getConfigJson() {
        return configJson;
    }

    public void setConfigJson(String configJson) {
        this.configJson = configJson;
    }

    public String getSqlTemplate() {
        return sqlTemplate;
    }

    public void setSqlTemplate(String sqlTemplate) {
        this.sqlTemplate = sqlTemplate;
    }

    public String getDenominatorSqlTemplate() {
        return denominatorSqlTemplate;
    }

    public void setDenominatorSqlTemplate(String denominatorSqlTemplate) {
        this.denominatorSqlTemplate = denominatorSqlTemplate;
    }

    public String getMetaJson() {
        return metaJson;
    }

    public void setMetaJson(String metaJson) {
        this.metaJson = metaJson;
    }

    // -------------------------------------------------
    // Helpers
    // -------------------------------------------------

    public boolean isBase() {
        return kind == Kind.BASE;
    }

    public boolean isComposite() {
        return kind == Kind.COMPOSITE;
    }

    public boolean isFinal() {
        return kind == Kind.FINAL;
    }

    public String getKindLower() {
        return kind == null ? "" : kind.name().toLowerCase(Locale.ROOT);
    }

    // =====================================================
    // =============== INNER ENUM DEFINITIONS ==============
    // =====================================================

    public enum Kind {
        BASE,
        COMPOSITE,
        FINAL
    }

    public enum ValueType {
        NUMBER,
        TABLE,
        PATIENT_SET
    }

    public enum SqlMode {
        COUNT,
        PATIENT_SET
    }

    public enum CompositeOperator {
        AND,
        OR,
        A_AND_NOT_B
    }
}